### ISSUE TITLE
Enhancement: Option to turn off the what I'm assuming are debugging messages.

### ISSUE THREAD

**Issue by Calesta** [espenja/ArgusEliteTracker#4]
As per the subject line, please provide an option to turn off what appear to be debugging / status messages -- e.g., 'Argus Elite Tracker is hidden.'.

Thanks!

**Comment by espenja** [comment]
Thanks for notifying me, and thanks so much for creating issues here on github! All prints to the chat frame has been turned off in version 1.0.4. They can be enabled by setting the debug flag found in the top of ArgusEliteTracker.lua to true.
