### ISSUE TITLE
Enhancement: Remember window location between sessions.

### ISSUE THREAD

**Issue by Calesta** [espenja/ArgusEliteTracker#6]
As per my subject line, please enable some sort of saved variable that allows for the addon to 'remember' where we have the window placed on the screen.  Each time I close the game and come back into it, the window ends up in the center of the screen again.

Thanks!

**Comment by espenja** [comment]
This was a great annoyance for me as well. It was solved pretty easily by just giving the main frame a name. The location of the window should now be "memorized" by the game itself.
