### ISSUE TITLE
Enhancement: Alphabetize the list of rares in each zone.

### ISSUE THREAD

**Issue by Calesta** [espenja/ArgusEliteTracker#7]
Per the subject line, please alphabetize the list of rares in each zone.  Searching through that long Mac'Aree list can be tough! 

Thanks!

**Comment by espenja** [comment]
Adding this link, a user on curse.com already made some changes to allow for alphabetized list. [pastie](https://pastebin.com/AVig04wX)

**Comment by espenja** [comment]
Fixed in version 1.0.5
